import "./base.css";
import "./components.css";
import "./forms.css";
import "./gallery-faq.css";
import "./layout.css";
import "./tables.css";  
import { Space_Grotesk } from "next/font/google";

//import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={spaceGrotesk.variable}>
      <body>{children}</body>
    </html>
  );
}
